### ISSUE TITLE
Suggestion: Add minimum vote count to appear on leaderboard

### ISSUE THREAD

**Issue by pachonk** [pachonk/celebrity-picture-rater#45]
Currently we have 9 pictures that have 1 out of 1 vote: 
![image](https://user-images.githubusercontent.com/6721355/34799682-5109f16c-f626-11e7-982e-322df945e5a0.png)
What we could do is add a "minimum vote count" to appear on the leader board.

**Comment by d4rkd0s** [comment]
Yeah I mean the Algorithm should take this into play how can something with 1 vote beat something with 9? even if they are old...

**Comment by pachonk** [comment]
Idea: Boil down every comparison of picture A and B to be a majority vote of win or lose against all samples, then it gets a point if it beats an individual photo
Photos can have a max "point" ordering then of the number of photos - 1, so photos that don't have enough votes against enough other photos to be reputable won't be on the leaderboard until they can win against more other photos.
This solves the age thing pretty well and starts a sequencing that we can actually query for if it works, I just have to write the query and see how accurate it is thus far.

**Comment by pachonk** [comment]
It's the start of something good:

```sql
SELECT
  LEAST(left_picture_id, right_picture_id) AS least_picture_id,
  GREATEST(left_picture_id, right_picture_id) AS greatest_picture_id,
  SUM(CASE chosen_picture_id WHEN LEAST(left_picture_id, right_picture_id) THEN 1 END) as least_picture_wins,
  SUM(CASE chosen_picture_id WHEN GREATEST(left_picture_id, right_picture_id) THEN 1 END) AS greatest_picture_wins
FROM votes
GROUP BY LEAST(left_picture_id, right_picture_id), GREATEST(left_picture_id, right_picture_id)
ORDER BY COUNT(*) DESC
```
