### ISSUE TITLE
Provide an Elegant Color Scheme that is Easier on the Eyes (Dark theme)

### ISSUE THREAD

**Issue by pachonk** [pachonk/celebrity-picture-rater#54]
White is too hard on the eyes gaming and voting on pictures, we need something a little bit darker, even if it's only just off-white.

I'm really thinking full dark theme though.

**Comment by pachonk** [comment]
@d4rkd0s toss stylish script in here if you don't mind.

**Comment by d4rkd0s** [comment]
@pachonk its very simple, literally just this:

```
body {
    background: #0a0a0a;
    color: white;
}
```

**Comment by d4rkd0s** [comment]
Results in this:

![image](https://user-images.githubusercontent.com/2348814/39335887-c5b7748a-4969-11e8-8307-7e3766d01c82.png)

**Comment by pachonk** [comment]
Links looked off and looked a little extreme. Went with less contrasting colors in https://github.com/pachonk/celebrity-picture-rater/pull/73 but I'm open to tweaks
