### ISSUE TITLE
De-duplication with dupe-magick

### ISSUE THREAD

**Issue by d4rkd0s** [pachonk/celebrity-picture-rater#58]
Dupe-magick states, "If you need to look for duplicates which can't otherwise be found via md5 checksums e.g. images of different formats or slightly lossy, then this gem can compare or find duplicates based on euclidian distances between points in an 8x8x8 RGB vector cube."

https://rubygems.org/gems/dupe-magick

I think this would be a great feature to have since there isn't a directory of images users can view so duplicates are starting to become an issue.

**Comment by pachonk** [comment]
While I really appreciate your time to create this issue, unfortunately due to the additional get requests on s3 to do this on a worker pool, I'm going to have to reject this.
Once again, thank you for the research and time you put into this issue creation.
